### ISSUE TITLE
Linux version works on Ubuntu 16.04 LTS only

### ISSUE THREAD

**Issue by probonopd** [Przemol/seqplots_electron#1]
AppImage allows Linux applications to be packaged so that they run on different distributions. For example, the Seqplots AppImage launches just fine on openSUSE Leap 42.2, but then a window appears and says

> Only Ubuntu 16.04 LTS (Xenial Xerus) is supported by SeqPlots desktop app. Please update your system: http://releases.ubuntu.com/16.04/ or install R/Bioconductor version of SeqPlots: http://bioconductor.org/packages/seqplots

If you bundle the required dependencies inside the AppImage, then you could drop the requirement of one very specific distribution. But it will require more development, testing, and support work.

**Comment by Przemol** [comment]
Unfortunately the AppImage is shipped with specific compilation of R that requires libraries from  Ubuntu 16.04 LTS distro.

You can install R (https://www.r-project.org/) and from R run following code:
```
source("http://bioconductor.org/biocLite.R")
biocLite("seqplots")

if (!require("devtools")) install.packages("devtools")
devtools::install_github('przemol/seqplots', build_vignettes=FALSE)

library(seqplots)
run()
```

This method gives you the same functionality as stand-alone app and work across all Linux distributions.

**Comment by probonopd** [comment]
Please build the AppImage on the oldest still-supported distribution, e.g., Ubuntu 14.04 (trusty) at this time. For more information, please see https://docs.appimage.org/.
